### ISSUE TITLE
cortexbrain-tune.sh -> modprobe dhd

### ISSUE THREAD

**Issue by voku** [dorimanx/Dorimanx-SG2-I9100-Kernel#1]
[...]
if [ $cortexbrain_auto_tweak_wifi == on ]; then
    modprobe dhd 2>/dev/null;
fi;
[...]
if [ $cortexbrain_auto_tweak_wifi == on ]; then
    modprobe -r dhd 2>/dev/null;
fi;
[...]

<- if I tested this via "adb shell" it's working but it didn't work via shell-script ("cortexbrain-tune.sh") ?! Need more testing ...

**Comment by dorimanx** [comment]
fixed, see cortex :)
