### ISSUE TITLE
 mount internal sd as sdcard0. 

### ISSUE THREAD

**Issue by manan001** [dorimanx/Dorimanx-SG2-I9100-Kernel#12]
can you get kernel to mount internal sd as sdcard0. as there are few application that require this..
using 8.24 .. .facing the  mount internal sd as sdcard0 issue..

**Comment by dorimanx** [comment]
ROM type?
SAMMY?
or
CM/AOKP

**Comment by manan001** [comment]
Sammy sir

**Comment by manan001** [comment]
Sorry for late reply stock sammy bitfor rom.. right now using sammy kernel 8.24

**Comment by dorimanx** [comment]
Resolved!
https://github.com/dorimanx/initramfs3/commit/bdaf22d74ff9b70ffd3b1ffce1569cb9c66808a9
