### ISSUE TITLE
Mobile Data

### ISSUE THREAD

**Issue by ghost** [dorimanx/Dorimanx-SG2-I9100-Kernel#13]
I flashed 9.28 yesterday and it seemed to be completely alright, no sods, but then I tried to connect to the internet using mobile data and, although, it said ON I couldn't get access. Also, all the data activity history below vanished. I would appreciate some help. 

ROM: Pacman v22.2

**Comment by dorimanx** [comment]
use XDA tread, this is DEV ONLY place.

**Comment by ghost** [comment]
Sorry, I was not aware.
