### ISSUE TITLE
Dorimanx 9.XX - Hotmixradio app

### ISSUE THREAD

**Issue by GaborToulouse** [dorimanx/Dorimanx-SG2-I9100-Kernel#16]
Hello guys !

Samsung Galaxy S2
CyanogenMod Nightly 10.1-20130718-NIGHTLY-i9100
Dorimanx 9.35

I used CyanogenMod Nightlies since months.
I use Hotmixradio application.
All was OK, but the battery drain was making me a bit angry.

So I decided to install Dorimanx Kernel 
Now, everytime I install a new CM Nightlies 10.1 (CyanDelta), I install the last Dorimanx Kernel 9.XX.

The problem is that when I only install CM Nightly, Hotmixradio is OK.
But when I install Dorimanx, Hotmixradio doesnt work anymore : in french, the error is "Erreur du flux. Recommencer plus tard". It could be translated by "Flow error. Try again later".

What I tried :
Installing properly the Kernel after CM 10.1 (Clear Dalvik, fix permissions, Clear Cache, install Kernel, Clear Dalvik, fix permissions, Clear Cache)
Uninstall/install Hotmixradio
Wifi, not wifi, 3G, 2G network
Restore Hotmixradio using Titanium Backup
Tried a lot of configurations in STweaks

Note : I use Dorimanx since version 9.27

Note 2 : I uploaded the 2 logs by adding a ".jpg" extension to files, because GitHub does NOT want other files than Pictures...

Any idea ?

Thx a lot !

Gabor, Toulouse
France
Samsung Galaxy S2
CyanogenMod Nightly 10.1-20130718-NIGHTLY-i9100
Dorimanx 9.35

![screenshot_2013-07-18-14-46-28](https://f.cloud.github.com/assets/5039430/819111/2a8b0c78-efab-11e2-8638-ef7c9edd7298.png)

![dorimanx_debug](https://f.cloud.github.com/assets/5039430/819133/b4a8736e-efab-11e2-8980-5c08d499698a.jpg)
![dorimanx_debug_logcat](https://f.cloud.github.com/assets/5039430/819134/b4a92598-efab-11e2-89b0-8128b0c8e7e9.jpg)

**Comment by GaborToulouse** [comment]
I already talk about that problem to Hotmixradio team : they never had this problem.
I dont find any information of this problem anywhere.
-> That's why I think the problem is in dorimanx Kernel.

**Comment by g-goessel** [comment]
No problem here with latest rootbox nightly and 9.35. So no kernel related.
Try to reinstall the app

**Comment by GaborToulouse** [comment]
There is clearly a problem between CM 10.1 and Dorimanx Kernel with this app (and may be others, that's why I opened this thread).

I just installed the last CM Nitghly for July, 19th, (and as always the Dorimanx 9.35).
I launched Hotmixradio : it is OK.
I quit Hotmixradio and launch it again : it is OK.

So i'm happy... for some minutes...

Yes, because some minutes later, I try it again : the error appeared again.
And now, I'm unable to make work Hotmixradio again... Always the same message.

For installing/reinstalling : I tried it again... As I already told it, that is not better...

Clearing Dalvik and cache in recovyer is not better...

**Comment by dorimanx** [comment]
I have installed the APP.
i use rootbox last nightly.

SO, the DANCE not working! as you say.
in LOGS!
E/com.liquidair.apptronic.AppActivity(22542): Stream error
E/com.liquidair.apptronic.AppActivity(22542): java.io.IOException: HTTP/1.0 404 Not Available
E/com.liquidair.apptronic.AppActivity(22542):   at com.liquidair.spodtronic.stream.StreamInputStream.checkRedirects(StreamInputStream.java:311)
E/com.liquidair.apptronic.AppActivity(22542):   at com.liquidair.spodtronic.stream.StreamInputStream.connect(StreamInputStream.java:117)
E/com.liquidair.apptronic.AppActivity(22542):   at com.liquidair.spodtronic.httpserver.StreamerServer.doPrepareStreamAsync(StreamerServer.java:427)
E/com.liquidair.apptronic.AppActivity(22542):   at com.liquidair.spodtronic.httpserver.StreamerServer.access$6(StreamerServer.java:417)
E/com.liquidair.apptronic.AppActivity(22542):   at com.liquidair.spodtronic.httpserver.StreamerServer$1.run(StreamerServer.java:410)
W/SingleClientConnManager(22542): Invalid use of SingleClientConnManager: connection still allocated.
W/SingleClientConnManager(22542): Make sure to release the connection before allocating another one.

the LINK to that stream is not exist! HTTP/1.0 404 Not Available!!!!!

all the rest streams WORK, every one of them!
what do you want from me???

Please do not OPEN case here for APPS, it's not the place.

**Comment by GaborToulouse** [comment]
Hello,

Sorry, was only here to help
1. I'm IT in publishing medical software. We have a team support and customers, and a procedure for them to report bugs to us. I know how support works.
2. I tried to provide you all the informations I had
3. CM 10.1 Nightly + Hotmixradio = OK. As soon as I put the Dorimanx Kernel : problem
4. Tried a lot of other ROMS before, and I never had the problem
5. In Hotmixradio, the problem is not only on "Dance Channel" : it is on ALL channels
6. I tried all that I can to avoid the problem, providing you all the methods I used to repair ; u did not even try to provide me ONE useful information.
7. I DO know that Hotmixradio is NOT a soft you manage. I DO know that it is an external application. But I was wondering if this problem with Hotmixradio was not the "top of the iceberg", hiding worst problems.
8. U dont want my help anymore. OK, so I forgot Dorimanx kernel, and only use CM 10.1 with native kernel or other kernel. Or may be I'll continue using Dorimanx : after all, Hotmixradio not working is not the worst problem in the world for me.

I close the ticket. Sorry for trying to help you.

**Comment by dorimanx** [comment]
OK, i have made some tests, and found that some part of internet links to streaming are blocked by AD-BLOCKER file!

/system/etc/hosts

if you have ONE or using some AD BLOCK app, REMOVE the APP and remove the AD-BLOCK via STweaks OTHER tab.

REBOOT, and have fun! but you get all the shit load of adds from all APPS, this APP work on ADDS, this is there money! if you block the adds, they block your music channel.

choose what you want more :)

Can't bind to a link-local address without a scope id: localhost/::1

all adds links are pushed to LOCALHOST! :) no adds no music

good day..

**Comment by GaborToulouse** [comment]
That's very nice.
It works fine.

I was wondering if some proxy or kind of soft was not blocking Hotmixradio... I have my answer ;-)
It is a kind of "forced proxy" ;-)

Thank you a lot.

Just for information, AD Blocker doesnt seem to work ALWAYS, because I was successful in using Hotmixradio 2 times before AD Blocker block it. Any other problem may be ?

At last, I thank you very much.

Gabor, Toulouse
France
