### ISSUE TITLE
CM10: symlink for /mnt/sdcard/ doesn't exists 

### ISSUE THREAD

**Issue by voku** [dorimanx/Dorimanx-SG2-I9100-Kernel#2]
I use CM10 and I have the problem that the mount-point for /mnt/sdcard/ & /mnt/emmc/ are missing ... so I can't start some Apps :P (with default CM10-kernel this problem doesn't exists)

---

/mnt $ ls -al
ls -al
drwxrwxr-x   10 root     system           0 Aug 30 09:08 .
drwxr-xr-x   19 root     root             0 Aug 30 09:08 ..
drwxr-xr-x    1 root     root             0 Jan  1  1970 .lfs
drwxr-xr-x    2 root     system          40 Aug 30 09:08 asec
drwxr-xr-x    2 system   system           0 Aug 30 10:59 emmc
lrwxrwxrwx    1 root     root            16 Aug 30 09:08 extSdCard -> /storage/sdcard1
drwxrwxrwx    2 root     root            40 Aug 30 09:08 ntfs
drwxr-xr-x    2 root     system          40 Aug 30 09:08 obb
drwxr-xr-x    2 system   system           0 Aug 30 10:59 sdcard
drwx------    4 root     root             0 Aug 30 09:08 secure
drwxr-xr-x    2 system   system           0 Aug 30 10:59 usbdisk
lrwxrwxrwx    1 root     root            17 Aug 30 09:08 usbdisk0 -> /storage/usbdisk0

---

... we already try to to add a link for this mount-points but this don't work, because (I think) there are still directories with the same name in /mnt/ ...

-> https://github.com/dorimanx/initramfs3/blob/master/res/misc/JellyB-CM-AOKP/init.smdk4210.rc -> 

---
# for backwards compatibility

```
symlink /storage/sdcard0 /sdcard
symlink /storage/sdcard0 /mnt/sdcard
symlink /storage/sdcard1 /extSdCard
symlink /storage/sdcard1 /mnt/extSdCard
symlink /storage/usbdisk0 /usbdisk0
symlink /storage/usbdisk0 /mnt/usbdisk0
```

---

**Comment by dorimanx** [comment]
Fixed in 5.71! thanks for report!
