### ISSUE TITLE
Games freezing

### ISSUE THREAD

**Issue by armac911** [dorimanx/Dorimanx-SG2-I9100-Kernel#23]
This bug occurs on all roms (even stock sammy JB) when using DorimanX kernel for the appropriate rom (both 9.x and 8.x for samsung stock). The rom and kernel version mentioned below correspond with the log file provided. The official samsung JB firmware (with stock kernel) is not locking up the phone, but all newer CM roms (and sentinel) do. 

Samsung Galaxy S2 - i9100 (int)
Kernel: Kernel_Dorimanx-V9.41-[15-19]-[23-09]-JB-SGII-PWR-CORE.zip
Rom:  SentinelROM v4.80

What happens: 
GPU Intensive games such as "Need for speed: Most Wanted", "Real Racing 3", freeze shortly after starting, completely locking the device and the sound in place. Battery pull or holding power is the only way to turn off the phone. I should mention that this happens when the GPU is starting to render the 3D environment (e.g. doesn't freeze in menus)

What should happen:
Should not freeze

What I tried:
Various tweaks in ST, forcing GPU in dev., disabling HW overlays. Lowering the GPU clock to sub 200 Mhz seems to be working better, but still freezing occasionally. 

Log file. The log is dumping data in .txt file until the phone freezes and adb disconnects.

Pastebin: http://pastebin.com/uUS9TJ75
or download: https://sites.google.com/site/ssh3mk/stuff/logcat-games.zip

**Comment by dorimanx** [comment]
not freeze here, and with my beta testers. so its your device compatibility problem, or outdated rom.
