### ISSUE TITLE
FC's on MIUI kitkat 

### ISSUE THREAD

**Issue by blackfa1con** [dorimanx/Dorimanx-SG2-I9100-Kernel#36]
My rom based on PAC-ROM and it work fine , but when i open the Phone and Contacts app its fc and android.process.core appear ! 

i think the problem in the kernel because when i use the cyanogenmod kernel it work fine and the fc disappear .

 ~ note that i built the Miui and the Pac from source ~ 

also i built the kernel from source too , and i wanna use your kernel in my rom , so please give me a hint to solve the problem :) 

thank you .

**Comment by dorimanx** [comment]
Inspect ramdisk init files for framework jar files include, that i dont have for your rom.

**Comment by blackfa1con** [comment]
Ok , I got it ..
You mean I need to unpack boot.img 
So I will have the ramdisk files and then I modified the init.rc to point the frameworks ? 
The issue not in the kernel build , its in ramdisk files , right ? 
Also can I include your kernel zimage in the boot.img file ? 
Sorry I'm new in this game :D .

**Comment by dorimanx** [comment]
You cant just use your ramdisk with my kernel. You need to unpack your ramdisk, inspect init files, compare to my, find the missing jar include, and add it in my ramdisk in same file.
Compile my kernel, and use.

**Comment by blackfa1con** [comment]
Thank you man for your help , after hours in testing i found the problem .
the problem not in ramdisk or anything else inside the kernel repo , i found that some files ( libsqlite.so ) ( sqlite ) in initramfs3 repo , make a fc's in any app that using it like Phone Or Contact apps .
so i modified it and the rom working fine now :) .
