### ISSUE TITLE
Stweks kernel not supported 

### ISSUE THREAD

**Issue by blackfa1con** [dorimanx/Dorimanx-SG2-I9100-Kernel#37]
There's a problem after flash the dorimanX kernel , stweaks say no kernel support , can you help me to resolve the issue ...
Maybe the problem in permissions or something else about UCI.sh file ? 
Note that when I flash your pre compiled kernel it work , but when I compile my own the issue appear 
Thank you :)

**Comment by dorimanx** [comment]
Kernel is not supported any more. You made mistake. Search for it.
