### ISSUE TITLE
Wifi freeze

### ISSUE THREAD

**Issue by dhilipkr** [dorimanx/Dorimanx-SG2-I9100-Kernel#5]
I use the 'Juice defender' application wherein I configure it for periodic syncing of e-mails when connected over wifi. Almost once in 3 days my phone freezes and the screen doesn't wake up at all. Sometimes it gets switched off completely. I have seen this with Samsung Stock ICS of galaxy s2. And that is the reason I switched to Jellybam with Dorimanx kernel. I am currently using kernel version 7.4.2  and Jellybam  version 20121120. I don't see this problem when I disable the 'Juice defender' app. I have tried your kernel version 7.22, 7.23 and faced the same problem. This issue is not seen only by me but also by 2 of my colleagues who have the same i9100  with Samsung stock ICS and dorimanx kernel version 5.90.

**Comment by voku** [comment]
can you please add some logs, thx! -> http://dorimanx.suckup.de/dorimanx-kernel-for-sg2-i9100/howto-report-bugs/

PS: you can simply push the debug-button via STweaks-App

**Comment by dhilipkr** [comment]
The problem that I describe happens mostly when I just pick up the phone and try to turn on the screen and then it just doesn't respond at all even if I press any of the hard keys.  And then I connect the USB port to check via adb if at all the device is alive or not. And sometimes adb just doesn't list the device (in which case I would assume the phone has turned off completely). but sometimes it does respond but the phone screen never works. Is there a way to invoke the stweaks logging from adb shell? If yes, then the next time I hit this, I can try invoking from adb shell to take the dump.

**Comment by voku** [comment]
Take a look at the link I posted -> 3.2) Create some debug-logs via “adb” or “ExTweaks”-App

**Comment by dorimanx** [comment]
we are working on stuck solution.
