### ISSUE TITLE
video recording not working on stock modefied rom JB 4.1.2

### ISSUE THREAD

**Issue by manan001** [dorimanx/Dorimanx-SG2-I9100-Kernel#6]
video recording does not work on sammy stock roms. 

when video start recording it hangs and gives error..

sorry for the half info..
phone model  gt 9100
stock rom neatrom 4.0 lite

JB rom stock... sir... 
after instilling 7.36 following problems are faced
1- signal problem keeps dropping
2- wifi issue
3 video recording broken. when clicking on video recording it will beep and show error message cannot be started.
4- once even the phone restarted.

thanks for listening,.

sir i dont use CM ROM 10.1 as it has radio problem as stock radio does not work with it. and sprint radio needs Bluetooth to be on.

**Comment by dorimanx** [comment]
problem known for JB SAMMY.
you didnt gave full problem info.

on what TYPE of Stock ROM camera DONT WORK.
ICS or JB Stock.

without full info, issue will be closed.

**Comment by nij4t** [comment]
When I open the stock Video Player it always crashes. It may be problems with HW, coz the videoplayer on omega rom has autoplay feature. Please, run and check it out.

**Comment by dorimanx** [comment]
problem with video player is KNOWN use search in question thread.
update to last kernel.

case closed.
