### ISSUE TITLE
random crashs

### ISSUE THREAD

**Issue by Mettafox** [dorimanx/Dorimanx-SG2-I9100-Kernel#7]
ROM: SuperNexus 2.0 Build 3 (Android 4.2.2)
Kernel: Kernel_Siyah-Dorimanx-V7.47-[02-10]-[07-02]-ICS-JB-SGII-PWR-CORE

Gives random crashes and need remove the battery and restart the device to solve.
Default profile in the STweaks.

The crashes mostly happen when the device enter in the sleep mode (screen off), but, I have another crash out of the sleep mode situation.

3 crashs after I installed the kernel, at moment, no random reboots.

**Comment by g-goessel** [comment]
Logs ?

**Comment by Mettafox** [comment]
How I can do a log if I don't know when the crash will happen?

Anyone?

**Comment by dorimanx** [comment]
you dont.
wait for next kernel.
this is not place for cases without any LOGS or info.
bye.
