### ISSUE TITLE
Incorrect ROM version detected on boot

### ISSUE THREAD

**Issue by DragoonAethis** [dorimanx/Dorimanx-SG2-I9100-Kernel#9]
Since I still can't post in the development thread, and there is **no** log...

Installed [AOKP 4.1.2 Milestone 1](http://goo.im/devs/aokp/i9100/aokp_i9100_jb_milestone-1.zip), then GApps for 4.1.2, and V9.14 of this kernel. It's AOSP-based JB, should work, but the kernel detects AOKP as Sammy JB, displays a "I'm going to have a heart attack" image, and reboots afterwards. There are no logs (couldn't connect it via ADB), installing Siyah 5.0.1 makes it work again. Version detection should be improved.

AOKP 4.2.2 Milestone 1 is detected fine, boots and works perfectly.

**Comment by dorimanx** [comment]
i need the build.prop to fix,
if you ever want to open case, give the DEV info, not bull shit.
